In [51]:
print ("hola mundo")

hola mundo

# 1. Carga, inspección y validación de datos correctamente
notas: Cargar_datos.ipynb: Este notebook no se utiliza normalmente en el proceso de creación de un modelo dado que nuestra data deberá estar en el DWH o Datalake de la empresa como resultado de un proceso diferente que materialice nuestra información en una tabla. Sin embargo, para este caso, se utiliza un dataset no productivo de ejemplo en .csv.

# Importar Librerias

In [52]:
#Importar librerías
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
print ("librerías importadas correctamente")

librerías importadas correctamente

## 1.1 Carga de datos

In [61]:
#cargar datos
df = pd.read_excel('../../Base_de_datos.xlsx')
print ("datos cargados correctamente")
print("=" * 100)

datos cargados correctamente
====================================================================================================

1.2 Inspección de datos

In [64]:
#tamaño del dataset
print(f"El dataset tiene {df.shape[0]} filas y {df.shape[1]} columnas.")
print("=" * 100)

El dataset tiene 10763 filas y 23 columnas.
====================================================================================================

In [54]:
display(df.head()) 
print("=" * 100)

,tipo_credito,fecha_prestamo,capital_prestado,plazo_meses,edad_cliente,tipo_laboral,salario_cliente,total_otros_prestamos,cuota_pactada,puntaje,...,saldo_mora,saldo_total,saldo_principal,saldo_mora_codeudor,creditos_sectorFinanciero,creditos_sectorCooperativo,creditos_sectorReal,promedio_ingresos_datacredito,tendencia_ingresos,Pago_atiempo
0,7,2024-12-21 11:31:35,3692160.0,10,42,Independiente,8000000,2500000,341296,88.768094,...,0.0,51258.0,51258.0,0.0,5,0,0,908526.0,Estable,1
1,4,2025-04-22 09:47:35,840000.0,6,60,Empleado,3000000,2000000,124876,95.227787,...,0.0,8673.0,8673.0,0.0,0,0,2,939017.0,Creciente,1
2,9,2026-01-08 12:22:40,5974028.4,10,36,Independiente,4036000,829000,529554,47.613894,...,0.0,18702.0,18702.0,0.0,3,0,0,NaN,NaN,0
3,4,2025-08-04 12:04:10,1671240.0,6,48,Empleado,1524547,498000,252420,95.227787,...,0.0,15782.0,15782.0,0.0,3,0,0,1536193.0,Creciente,1
4,9,2025-04-26 11:24:26,2781636.0,11,44,Empleado,5000000,4000000,217037,95.227787,...,0.0,204804.0,204804.0,0.0,3,0,1,933473.0,Creciente,1

====================================================================================================

In [ ]:
df

In [55]:
# Descripcion de las variables
descripciones = {
    'tipo_credito': 'Tipo de crédito solicitado (ej. personal, hipotecario).',
    'fecha_prestamo': 'Fecha en que se otorgó el préstamo.',
    'capital_prestado': 'Monto del capital prestado.',
    'plazo_meses': 'Plazo del préstamo en meses.',
    'edad_cliente': 'Edad del cliente.',
    'tipo_laboral': 'Tipo de empleo del cliente (ej. independiente, empleado).',
    'salario_cliente': 'Salario mensual del cliente.',
    'total_otros_prestamos': 'Monto total de otros préstamos activos.',
    'cuota_pactada': 'Cuota mensual acordada para el pago.',
    'puntaje': 'Puntaje de crédito interno.',
    'puntaje_datacredito': 'Puntaje de Datacrédito (buró de crédito).',
    'cant_creditosvigentes': 'Cantidad de créditos vigentes.',
    'huella_consulta': 'Número de consultas al historial crediticio.',
    'saldo_mora': 'Saldo en mora (deudas vencidas).',
    'saldo_total': 'Saldo total del crédito.',
    'saldo_principal': 'Saldo del capital principal pendiente.',
    'saldo_mora_codeudor': 'Saldo en mora del codeudor.',
    'creditos_sectorFinanciero': 'Número de créditos en el sector financiero.',
    'creditos_sectorCooperativo': 'Número de créditos en cooperativas.',
    'creditos_sectorReal': 'Número de créditos en el sector real (comercio, etc.).',
    'promedio_ingresos_datacredito': 'Promedio de ingresos reportados en Datacrédito.',
    'tendencia_ingresos': 'Tendencia de los ingresos (Estable, creciente o decreciente).',
    'Pago_atiempo': 'Indicador de pago a tiempo (variable objetivo: 1 si paga a tiempo, 0 si no).'
}

for var, desc in descripciones.items():
    print(f"{var}: {desc}")
print("=" * 100)

tipo_credito: Tipo de crédito solicitado (ej. personal, hipotecario).
fecha_prestamo: Fecha en que se otorgó el préstamo.
capital_prestado: Monto del capital prestado.
plazo_meses: Plazo del préstamo en meses.
edad_cliente: Edad del cliente.
tipo_laboral: Tipo de empleo del cliente (ej. independiente, empleado).
salario_cliente: Salario mensual del cliente.
total_otros_prestamos: Monto total de otros préstamos activos.
cuota_pactada: Cuota mensual acordada para el pago.
puntaje: Puntaje de crédito interno.
puntaje_datacredito: Puntaje de Datacrédito (buró de crédito).
cant_creditosvigentes: Cantidad de créditos vigentes.
huella_consulta: Número de consultas al historial crediticio.
saldo_mora: Saldo en mora (deudas vencidas).
saldo_total: Saldo total del crédito.
saldo_principal: Saldo del capital principal pendiente.
saldo_mora_codeudor: Saldo en mora del codeudor.
creditos_sectorFinanciero: Número de créditos en el sector financiero.
creditos_sectorCooperativo: Número de créditos en cooperativas.
creditos_sectorReal: Número de créditos en el sector real (comercio, etc.).
promedio_ingresos_datacredito: Promedio de ingresos reportados en Datacrédito.
tendencia_ingresos: Tendencia de los ingresos (Estable, creciente o decreciente).
Pago_atiempo: Indicador de pago a tiempo (variable objetivo: 1 si paga a tiempo, 0 si no).
====================================================================================================

### Datos consistentes de tipo esperado.

In [56]:
print("\nInformación general del conjunto de datos:") 
df.info()
print("=" * 100)

Información general del conjunto de datos:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10763 entries, 0 to 10762
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   tipo_credito                   10763 non-null  int64
 1   fecha_prestamo                 10763 non-null  datetime64[ns]
 2   capital_prestado               10763 non-null  float64
 3   plazo_meses                    10763 non-null  int64
 4   edad_cliente                   10763 non-null  int64
 5   tipo_laboral                   10763 non-null  object
 6   salario_cliente                10763 non-null  int64
 7   total_otros_prestamos          10763 non-null  int64
 8   cuota_pactada                  10763 non-null  int64
 9   puntaje                        10763 non-null  float64
 10  puntaje_datacredito            10757 non-null  float64
 11  cant_creditosvigentes          10763 non-null  int64
 12  huella_consulta                10763 non-null  int64
 13  saldo_mora                     10607 non-null  float64
 14  saldo_total                    10607 non-null  float64
 15  saldo_principal                10358 non-null  float64
 16  saldo_mora_codeudor            10173 non-null  float64
 17  creditos_sectorFinanciero      10763 non-null  int64
 18  creditos_sectorCooperativo     10763 non-null  int64
 19  creditos_sectorReal            10763 non-null  int64
 20  promedio_ingresos_datacredito  7833 non-null   float64
 21  tendencia_ingresos             7831 non-null   object
 22  Pago_atiempo                   10763 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(12), object(2)
memory usage: 1.9+ MB
====================================================================================================

In [70]:
# descripcion estadística de las variables numéricas
print("\nDescripción estadística de las variables numéricas:")
display(df.describe())
print("=" * 100)

Descripción estadística de las variables numéricas:

,tipo_credito,fecha_prestamo,capital_prestado,plazo_meses,edad_cliente,salario_cliente,total_otros_prestamos,cuota_pactada,puntaje,puntaje_datacredito,...,huella_consulta,saldo_mora,saldo_total,saldo_principal,saldo_mora_codeudor,creditos_sectorFinanciero,creditos_sectorCooperativo,creditos_sectorReal,promedio_ingresos_datacredito,Pago_atiempo
count,10763.000000,10763,1.076300e+04,10763.000000,10763.000000,1.076300e+04,1.076300e+04,1.076300e+04,10763.000000,10757.000000,...,10763.000000,10607.000000,1.060700e+04,1.035800e+04,10173.000000,10763.000000,10763.000000,10763.000000,7.833000e+03,10763.000000
mean,5.411131,2025-04-16 23:06:02.111121664,2.434315e+06,10.575583,43.948620,1.721643e+07,6.238870e+06,2.436174e+05,91.170036,780.790834,...,4.228561,7.746017,4.593741e+04,4.034617e+04,0.260002,2.779987,0.269813,1.302704,2.005157e+06,0.952523
min,4.000000,2024-11-26 09:17:04,3.600000e+05,2.000000,19.000000,0.000000e+00,0.000000e+00,2.394400e+04,-38.009990,-7.000000,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,4.000000,2025-01-20 17:33:07.500000,1.224831e+06,6.000000,33.000000,2.000000e+06,5.000000e+05,1.210415e+05,95.227787,757.000000,...,2.000000,0.000000,2.898000e+03,2.690000e+03,0.000000,1.000000,0.000000,0.000000,9.251570e+05,1.000000
50%,4.000000,2025-03-27 16:23:12,1.921920e+06,10.000000,42.000000,3.000000e+06,1.000000e+06,1.828630e+05,95.227787,791.000000,...,4.000000,0.000000,1.617800e+04,1.444250e+04,0.000000,2.000000,0.000000,1.000000,1.204496e+06,1.000000
75%,9.000000,2025-06-16 13:27:58,3.084840e+06,12.000000,53.000000,4.875808e+06,2.000000e+06,2.878335e+05,95.227787,825.000000,...,6.000000,0.000000,5.298200e+04,4.763225e+04,0.000000,4.000000,0.000000,2.000000,2.231859e+06,1.000000
max,68.000000,2026-04-26 18:43:52,4.144415e+07,90.000000,123.000000,2.200000e+10,6.787675e+09,3.816752e+06,95.227787,999.000000,...,29.000000,12534.000000,5.116066e+06,1.562285e+06,2145.000000,51.000000,13.000000,25.000000,3.810658e+07,1.000000
std,2.338279,NaN,1.909643e+06,6.632082,15.060877,3.554767e+08,1.184183e+08,2.104937e+05,16.465441,104.878031,...,3.064683,225.955117,1.062698e+05,7.124244e+04,21.772917,2.748807,0.716471,1.824430,2.144116e+06,0.212668

====================================================================================================

# 1.2 Validación de datos (Proceso de verificar que los datos sean correctos, completos y útiles antes de ser procesados o almacenados. )

In [72]:
#rangos de las variables numéricas
print("\nRangos de las variables numéricas:")
for col in df.select_dtypes(include=['int64', 'float64']).columns:
    print(f"{col}: {df[col].min():,} - {df[col].max():,}")  
print("=" * 100)

Rangos de las variables numéricas:
tipo_credito: 4 - 68
capital_prestado: 360,000.0 - 41,444,152.8
plazo_meses: 2 - 90
edad_cliente: 19 - 123
salario_cliente: 0 - 22,000,000,000
total_otros_prestamos: 0 - 6,787,675,263
cuota_pactada: 23,944 - 3,816,752
puntaje: -38.00999 - 95.227787
puntaje_datacredito: -7.0 - 999.0
cant_creditosvigentes: 0 - 62
huella_consulta: 0 - 29
saldo_mora: 0.0 - 12,534.0
saldo_total: 0.0 - 5,116,066.0
saldo_principal: 0.0 - 1,562,285.0
saldo_mora_codeudor: 0.0 - 2,145.0
creditos_sectorFinanciero: 0 - 51
creditos_sectorCooperativo: 0 - 13
creditos_sectorReal: 0 - 25
promedio_ingresos_datacredito: 0.0 - 38,106,581.0
Pago_atiempo: 0 - 1
====================================================================================================

### Edad con valores incoherentes a la realidad

## Valores Nulos
Se observa que seis (6) de las columnas presentan valores nulos para su posterior tratamiento.

In [68]:
print("\nValores nulos en cada columna:")   
print(df.isnull().sum())  
print("=" * 100)

Valores nulos en cada columna:
tipo_credito                        0
fecha_prestamo                      0
capital_prestado                    0
plazo_meses                         0
edad_cliente                        0
tipo_laboral                        0
salario_cliente                     0
total_otros_prestamos               0
cuota_pactada                       0
puntaje                             0
puntaje_datacredito                 6
cant_creditosvigentes               0
huella_consulta                     0
saldo_mora                        156
saldo_total                       156
saldo_principal                   405
saldo_mora_codeudor               590
creditos_sectorFinanciero           0
creditos_sectorCooperativo          0
creditos_sectorReal                 0
promedio_ingresos_datacredito    2930
tendencia_ingresos               2932
Pago_atiempo                        0
dtype: int64
====================================================================================================

## Valores duplicados 
Se observa que no hay duplicidad de valores

In [59]:
# ver duplicados
print("\nRegistros duplicados:")
print(df.duplicated().sum())
print("=" * 100)

Registros duplicados:
0
====================================================================================================

In [65]:
# ver valores unicos
print("\nValores únicos por columna:")
for col in df.columns:
    unique_vals = df[col].nunique()
    print(f"{col}: {unique_vals} valores únicos")
print("=" * 100)

Valores únicos por columna:
tipo_credito: 6 valores únicos
fecha_prestamo: 10758 valores únicos
capital_prestado: 7306 valores únicos
plazo_meses: 18 valores únicos
edad_cliente: 54 valores únicos
tipo_laboral: 2 valores únicos
salario_cliente: 1385 valores únicos
total_otros_prestamos: 1538 valores únicos
cuota_pactada: 9836 valores únicos
puntaje: 248 valores únicos
puntaje_datacredito: 315 valores únicos
cant_creditosvigentes: 39 valores únicos
huella_consulta: 28 valores únicos
saldo_mora: 55 valores únicos
saldo_total: 8858 valores únicos
saldo_principal: 8647 valores únicos
saldo_mora_codeudor: 4 valores únicos
creditos_sectorFinanciero: 33 valores únicos
creditos_sectorCooperativo: 11 valores únicos
creditos_sectorReal: 24 valores únicos
promedio_ingresos_datacredito: 5309 valores únicos
tendencia_ingresos: 46 valores únicos
Pago_atiempo: 2 valores únicos
====================================================================================================